# Generated by Django 3.1.3 on 2020-11-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_processed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='predicted',
            field=models.IntegerField(null=True, verbose_name='Predicción spam/ham'),
        ),
        migrations.AlterField(
            model_name='emails',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='Asunto'),
        ),
    ]
