# Generated by Django 3.1.3 on 2020-12-07 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mail_processed', '0004_userextends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextends',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to=settings.AUTH_USER_MODEL),
        ),
    ]
