# Generated by Django 3.1.3 on 2020-12-14 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mail_processed', '0005_auto_20201207_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emails',
            old_name='content',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='emails',
            name='subject',
        ),
        migrations.AlterField(
            model_name='userextends',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuota', to=settings.AUTH_USER_MODEL),
        ),
    ]
